POST http://localhost:3001/api/notes 
Content-type: application/json

{
    "content": "Nota de ejemplo 2",
    "important": true,
    "userId": "606786c5a3ba6a2fc081b542"
}

###

POST http://localhost:3001/api/notes 
Content-type: application/json

{
}